exports.listCoffee = [
    { name: 'Эспрессо', price: 3.5 },
    { name: 'Американо', price: 4 },
    { name: 'Маленький Капучино', price: 4 },
    { name: 'Большой Капучино', price: 4.5 },
    { name: 'Маленький Латте', price: 4 },
    { name: 'Большой Латте', price: 4.5 },
    { name: 'Флэт Уайт', price: 4.5 },
    { name: 'Большой Раф', price: 4.8 },
    { name: 'Маленький Раф', price: 4.2 },
    { name: 'Маленький Мокко', price: 4.2 },
    { name: 'Большой Мокко', price: 4.8},
    { name: 'Детский Капучино', price: 2.5 },
    { name: 'Капучино апельсин-корица', price: 4.8 },
    { name: 'Горячий бамбл', price: 5 },
    { name: 'Капучино манго-питахайя', price: 4.8 },
    { name: 'Капучино кедр', price: 5.5 },
    { name: 'Латте голубика-асаи-лаванда', price: 4.8 },
    { name: 'Латте пшено', price: 5 },
    { name: 'Раф сырный', price: 5.5 },
    { name: 'Раф халва', price: 5 },
    { name: 'Сироп', price: 0.5 },
    { name: 'Растительное', price: 2 },
    { name: 'Молочко', price: 0.5 },
    { name: 'Пачка кофе 100г', price: 10 },
    { name: 'Пачка кофе 250г', price: 20 },
    { name: 'Пачка кофе 500г', price: 30 },
    { name: 'Пачка кофе 1кг', price: 50 }
];

exports.listHotDrinks = [
    { name: 'Какао', price: 4 },
    { name: 'Горячий шоколад', price: 4 },
    { name: 'Матча зеленая', price: 4.5 },
    { name: 'Матча синяя', price: 4.5 },
    { name: 'Облепиховый отвар', price: 4.5 },
    { name: 'Чай классика', price: 3.5 },
    { name: 'Чай фирменный', price: 4 },
    { name: 'Чай эксклюзивный', price: 4.5 },
];

exports.listColdDrinks = [
    { name: 'Айс Латте', price: 4.5 },
    { name: 'Айс Матча', price: 4.5 },
    { name: 'Бамбл', price: 5 },
    { name: 'Мазагран', price: 5 },
    { name: 'Эспресо тоник', price: 5 },
    { name: 'Малиновый рассвет', price: 4 },
    { name: 'Фруктовая вечеринка', price: 4 },
    { name: 'Ананасовый серфинг', price: 4 },
    { name: 'Молочный коктейль', price: 3.5 },
    { name: 'Шоколадный коктейль', price: 3.8 },
    { name: 'Ананасовый серфинг', price: 4 },
    { name: 'Rich апельсин', price: 2 },
    { name: 'Rich вишня', price: 2 },
    { name: 'Rich яблоко', price: 2 },
    { name: 'Добрый мультифрукт', price: 2 },
    { name: 'Бонаква', price: 1.5 },
    { name: 'Кола', price: 2 },
    { name: 'Фанта', price: 2 }
];

exports.listDeserts = [
    { name: 'Захер', price: 4.5 },
    { name: 'Картошка', price: 2 },
    { name: 'Красный бархат', price: 5 },
    { name: 'Маффин', price: 3 },
    { name: 'Медовик', price: 4.5 },
    { name: 'Молочная девочка', price: 3.5 },
    { name: 'Наполеон', price: 5 },
    { name: 'Нутэлла', price: 3.5 },
    { name: 'Олимпия', price: 3.5 },
    { name: 'Пирог яблоко-карамель', price: 5 },
    { name: 'Пончик с клубникой', price: 3 },
    { name: 'Пончик с маком', price: 3 },
    { name: 'Пончик с творогом', price: 3 },
    { name: 'Пончик с шоколадом', price: 3 },
    { name: 'Прага', price: 4.5 },
    { name: 'Пьяная вишня', price: 3.5 },
    { name: 'Сметанник', price: 4.5 },
    { name: 'Сникерс', price: 5 },
    { name: 'Трюфелька', price: 3.5 },
    { name: 'Чизкейк ореховый', price: 4 },
    { name: 'Чизкейк карамель', price: 4 },
    { name: 'Чизкейк малина', price: 4 },
    { name: 'Шу фисташка', price: 4 },
    { name: 'Шу ягоды', price: 4 },
    { name: 'Эклер с сырным кремом', price: 3.5 },
    { name: 'Эклер со сгущенкой', price: 3.5 },
    { name: 'Эклер шоколадный', price: 3.5 }
];

exports.listFood = [
    { name: 'Овсянка', price: 3.5 },
    { name: 'Яишенка', price: 4 },
    { name: 'Сырники', price: 5 },
    { name: 'По-американски', price: 5 },
    { name: 'По-итальянски', price: 5.5 },
    { name: 'По-камчатски', price: 6 },
    { name: 'По-французски', price: 6 },
    { name: 'Сладкий', price:  4.5},
];

exports.listBakery = [
    { name: 'Берлинер', price: 2.8 },
    { name: 'Булочка овсяная', price: 2.8 },
    { name: 'Кленовый пекан', price: 3 },
    { name: 'Крендель', price: 2.8 },
    { name: 'Круасан', price: 3.5 },
    { name: 'Пончик', price: 2.8 },
    { name: 'Розан с абрикосом', price: 3 },
    { name: 'Розан с малиной', price: 3 },
    { name: 'Твороженый твист', price: 3 }
];

exports.listBars = [
    { name: 'KIDAY', price: 1.5 },
    { name: 'Nut&Go', price: 1.0 },
    { name: "O'Zera вафля", price: 1 },
    { name: "O'Zera шоколадка", price: 1.5 },
    { name: 'Say No', price: 2 },
    { name: 'Зебра', price: 1 },
    { name: 'Крокант', price: 0.5 },
    { name: 'Мачос', price: 1 },
    { name: 'Предсказание', price: 1 },
    { name: 'Ritter Sport', price: 1.5 },
];